### ISSUE TITLE
Unable to complete installation

### ISSUE THREAD

**Issue by rain64x** [yanna92yar/open-listings#17]
<p align="center">
  <img src="http://i.countdownmail.com/2tvr2x.gif" border="0" alt="countdownmail.com"/> 
</p>

The post install command -  node-prune seems to fail on npm install

![image](https://github.com/yanna92yar/open-listings/assets/48401834/06d62a0c-b805-4d99-b31c-bbc155a27258)

**Comment by yanna92yar** [comment]
Please add node-prune toi dev dependencies. I'll be happy to merge a MR

**Comment by rain64x** [comment]
alright thank you

**Comment by yanna92yar** [comment]
Probably it needs to be installed globally as this is circular

**Comment by rain64x** [comment]
Please check PR #18

**Comment by yanna92yar** [comment]
Anyone landing here: please start from the second branch instead.
