### ISSUE TITLE
Implement a not found 404 page

### ISSUE THREAD

**Issue by yanna92yar** [yanna92yar/open-listings#5]

**Comment by yetea** [comment]
I'd like to work on this issue

**Comment by yanna92yar** [comment]
yse please, thanks a lot ^^

**Comment by yetea** [comment]
Thanks!

**Comment by yanna92yar** [comment]
Hi @yetea 
Any follow up? Issues with installation?

**Comment by yetea** [comment]
> Hi @yetea Any follow up? Issues with installation?

Hey, I've been quite busy the past week and haven't found the time to focus on this. I'll be finishing up with the project setup today and will get in touch with you if there's any issue.

**Comment by rayyyyofsunshine** [comment]
I am willing to work on this? Could you assign to me?

**Comment by lastuchiha** [comment]
Hey, I also want to work on this.
